// svelte/src/lib/CurrencyConverter.svelte
<script>
    import confetti from "canvas-confetti";

    let amount = $state(1)
    let rate = $state(1)

    const converted = $derived(amount*rate);
    function updateRate(){
        rate = Math.random() + 1;
    }

    $effect(()=>{
        console.log(rate, amount);
        confetti({
            particleCount: 100,
            spread: 70,
        });
    })
</script>


<div>
	<h1>Currency Converter</h1>
	<div>
		<label for="amount">Quinoa coin</label>
		<input type="number" id="amount" bind:value={amount} />
	</div>
	<div>
		<label for="rate">Doge coin rate</label>
		<span id="rate">{rate}</span>
		<button onclick={updateRate}>Update rate</button>
	</div>
	<p>Result: {converted} Doge coin</p>
</div>

// vue/src/components/CurrencyConverter.vue
<script setup>
import { ref, computed, watch } from 'vue'
import confetti from 'canvas-confetti'

const amount = ref(1)
const rate = ref(1)

const converted = computed(() => amount.value * rate.value)
watch([amount, rate], () => {
  confetti({
    particleCount: 100,
    spread: 70
  })
})
function updateRate() {
  rate.value = Math.random() + 1
}
</script>

<template>
  <div>
    <h1>Currency Converter</h1>
    <div>
      <label for="amount">Quinoa coin</label>
      <input type="number" id="amount" v-model="amount" />
    </div>
    <div>
      <label for="rate">Exchange rate</label>
      <span id="rate"> {{ rate }}</span>
      <button @click="updateRate">Update rate</button>
    </div>
    <p>Result: {{ converted }} Doge coin</p>
  </div>
</template>
