// angular/src/app/currency-converter/currency-converter.component.ts
import { Component, computed, effect, signal } from '@angular/core';

import confetti from 'canvas-confetti';

@Component({
  selector: 'app-currency-converter',
  standalone: true,
  imports: [],
  templateUrl: './currency-converter.component.html',
  styleUrl: './currency-converter.component.css',
})
export class CurrencyConverterComponent {
  amount = signal(1);
  rate = signal(1);
  converted = computed(() => this.amount() * this.rate());

  constructor() {
    effect(() => {
      console.log(this.amount(), this.rate());
      confetti({
        particleCount: 100,
        spread: 70,
      });
    });
  }

  updateRate() {
    this.rate.set(Math.random() + 1);
  }
}

<div>
  <h1>Currency Converter</h1>
  <div>
    <label for="amount">Quinoa coin</label>
    <input
      type="number"
      id="amount"
      [value]="amount()"
      (input)="amount.set($any($event.target).value || 1)"
    />
  </div>
  <div>
    <label for="rate">Exchange rate</label>
    <span id="rate"> {{ rate() }}</span>
    <button (click)="updateRate()">Update rate</button>
  </div>
  <p>Result: {{ converted() }} Doge coin</p>
</div>

// svelte/src/lib/CurrencyConverter.svelte
<script>
    import confetti from "canvas-confetti";

    let amount = $state(1)
    let rate = $state(1)

    const converted = $derived(amount*rate);
    function updateRate(){
        rate = Math.random() + 1;
    }

    $effect(()=>{
        console.log(rate, amount);
        confetti({
            particleCount: 100,
            spread: 70,
        });
    })
</script>


<div>
	<h1>Currency Converter</h1>
	<div>
		<label for="amount">Quinoa coin</label>
		<input type="number" id="amount" bind:value={amount} />
	</div>
	<div>
		<label for="rate">Doge coin rate</label>
		<span id="rate">{rate}</span>
		<button onclick={updateRate}>Update rate</button>
	</div>
	<p>Result: {converted} Doge coin</p>
</div>
